### PR TITLE
Use simplified argument for file flag

### PR DESCRIPTION
**Pull request by ctstone**
See #26

### CODE REVIEW

**Comment by cyberw** [comment]
Cool! I'd prefer dropping the old argument (having only one way to do it is better more important than backwards compatibility). Can you instead throw an error if someone tries to set it? Like (add this to somewhere around `__init__.py:48`)

    if environment.parsed_options.whatever_you_choose_to_rename_the_variable_for_the_old_param_to:
        sys.stderr.write(
            "--log_transactions_in_file=True has been replaced by --log-transactions-in-file\n"
        )
        sys.exit(1)

If you cannot be bothered, then just drop it and people will have to figure it out themselves.

**Comment by ctstone** [comment]
It's probably better to drop the old arg then. In order to detect the old arg, we would have to keep its `add_argument(..)` which means it will show up in the `--help` text.

I suppose we could inspect the raw `sys.argv` but maybe not worth the complexity.

**Comment by cyberw** [comment]
You can hide the argument by setting `help=configargparse.SUPPRESS`, like here https://github.com/locustio/locust/blob/0e362afa2c5931a906871bad2b7adc1caee8eee3/locust/argument_parser.py#L159

**Comment by ctstone** [comment]
Good to know! Added this

**Comment by cyberw** [comment]
Thx,

**Pull request merged**
