### PR TITLE
MQTT v5.0 support

### PR DESCRIPTION
**Pull request by ionutab**
Added different callback signatures in the `MqttClient` for

- on_connect
- on_disconnect

to support MQTT v5.0

As per the comments in the paho mqtt client:

```
        """The callback called when the broker reponds to our connection request.

        Expected signature for callback API version 2::

            connect_callback(client, userdata, connect_flags, reason_code, properties)

        Expected signature for callback API version 1 change with MQTT protocol version:
            * For MQTT v3.1 and v3.1.1 it's::

                connect_callback(client, userdata, flags, rc)

            * For MQTT v5.0 it's::

                connect_callback(client, userdata, flags, reason_code, properties)


        :param Client client: the client instance for this callback
        :param userdata: the private user data as set in Client() or user_data_set()
        :param ConnectFlags connect_flags: the flags for this connection
        :param ReasonCode reason_code: the connection reason code received from the broken.
                       In MQTT v5.0 it's the reason code defined by the standard.
                       In MQTT v3, we convert return code to a reason code, see
                       `convert_connack_rc_to_reason_code()`.
                       `ReasonCode` may be compared to integer.
        :param Properties properties: the MQTT v5.0 properties received from the broker.
                       For MQTT v3.1 and v3.1.1 properties is not provided and an empty Properties
                       object is always used.
        :param dict flags: response flags sent by the broker
        :param int rc: the connection result, should have a value of `ConnackCode`
"""
```

I'm not sure if anything can be done with the `properties` param passed in the callbacks.
Let me know if any changes are required.
Thanks!

### CODE REVIEW

**Comment by ionutab** [comment]
I'm not sure how to fix the linter issue.
I'm not sure why it is triggering for the `properties` but not for other cases in the file like:
```python
    def _on_connect_cb(
        self,
        client: mqtt.Client, # not used
        userdata: typing.Any, # not used
        flags: dict[str, int], # not used
        rc: int,
    ):
```
🤔

**Comment by cyberw** [comment]
No idea why it works in those other cases. Add `# pylint: disable=unused-argument` where you need it.

**Comment by cyberw** [comment]
Looks nice. Can you add setting the version to the example in mqtt_ex.py?

**Comment by ionutab** [comment]
> Looks nice. Can you add setting the version to the example in mqtt_ex.py?

I added it in `mqtt_custom_client.py`

Will add to `mqtt_ex.py` shortly.

**Comment by cyberw** [comment]
Ah, yes, I misread the PR :) But yes, I think it belongs in mqtt_ex.py only!

**Comment by ionutab** [comment]
> Ah, yes, I misread the PR :) But yes, I think it belongs in mqtt_ex.py only!

**Comment by ionutab** [comment]
please double check the code before merging - I had to alter the `MqttUser` to pass down the protocol.
thank you

**Pull request merged**
