### PR TITLE
Application insights listener

### PR DESCRIPTION
**Pull request by Guilhermeslucas**
This PR aims to add Azure application insights as the listener for locust results!
Azure application insights is a feature of Azure Monitor which is the central place to see the monitoring information about applications that are running on Azure. 
Application is specially useful when you want to see logs of your application, and in this case, how your load test performed!

### CODE REVIEW

**Comment by Guilhermeslucas** [comment]
I see all the checks are green, but it still pending! Anything I should do!

**Comment by cyberw** [comment]
Hi! Looks really cool!

* Please add an example to the /examples folder and an entry in README.md?
* Have you checked to see that AzureLogHandler is gevent-friendly? If it uses `requests` then it should be fine, otherwise it might block other greenlets/Users while sending its request.
* Can/should we batch loggings to make it more performant (like I do in TimescaleListener)? Or does AzureLogHandler maintain its own buffer somehow?
* Can you make it debugger friendly? When running a single locust in the debugger, there is no runner, so you’d need to make everything depending on a runner optional, like in TimescaleListener

**Comment by cyberw** [comment]
Oh, and is the name really correct, shouldnt it be AzureLogListener rather than ApplicationInsightsListener?

**Comment by Guilhermeslucas** [comment]
Thanks for the comments, Ill address them shortly! Regarding name, I feel ApplicationInsightsListener still makes more sense, logs can be put on some other places in Azure! Maybe AzureApplicationInsightsListener can make it more clear! What do you think?

**Comment by cyberw** [comment]
> Regarding name, I feel ApplicationInsightsListener still makes more sense, logs can be put on some other places in Azure! Maybe AzureApplicationInsightsListener can make it more clear! What do you think?

I honestly dont know any of these products, so your guess is probably better than mine :)

opencensus-ext-azure calls itself an ”OpenCensus Azure Monitor Exporter” and says it ”Exports data to Azure Monitor”. To me it sounds like this might be an AzureMonitorListener?

But I’ll leave it up to you :)

**Comment by Guilhermeslucas** [comment]
Application Insights is the tool to visualize logs, that is inside Azure Monitor. Azure monitor is a set of several tools for monitoring apps and infra, and Applications insights is one of them! The opencensus tells that cause it exports more than logs, is exports metrics, for example, that will be handled by other product inside Azure Monitor. Does that make sense? Nice discussion, btw! :)

**Comment by Guilhermeslucas** [comment]
Answering some of your questions:
- **Have you checked to see that AzureLogHandler is gevent-friendly?** It uses requests, as you can see by the logs 
image

- **Can/should we batch loggings to make it more performant (like I do in TimescaleListener)? Or does AzureLogHandler maintain its own buffer somehow?** This is something that OpenCensus deals extremely well! It already batches logs and send them from time to time, not sending each log at once.

Ill make it debugger friendly and add the examples as you asked, thanks!

**Comment by Guilhermeslucas** [comment]
I think all the things are fixed now!

**Comment by cyberw** [comment]
awesome, thanks!

**Pull request merged**
